name: swiss_knife
description: Dart Useful Tools - collections, math, date, uri, json, events, resources, regexp, etc...
version: 3.0.8
homepage: https://github.com/gmpassos/swiss_knife

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  intl: ^0.17.0
  resource_portable: ^3.0.0
  collection: ^1.15.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.9
  dependency_validator: ^3.1.0
  test_cov: ^1.0.1

#dependency_overrides:
#  resource_portable:
#    path: ../resource_portable

