name: swiss_knife
description: Dart Useful Tools - collections, math, date, uri, json, events, resources, regexp, etc...
version: 3.3.2
homepage: https://github.com/gmpassos/swiss_knife

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  intl: ^0.20.2
  resource_portable: ^3.1.2

dev_dependencies:
  lints: ^5.1.1
  test: ^1.26.3
  dependency_validator: ^5.0.2
  collection: ^1.19.1
  coverage: ^1.15.0

#dependency_overrides:
#  resource_portable:
#    path: ../resource_portable

