name: swiss_knife
description: Dart Useful Tools - collections, math, date, uri, json, events, resources, regexp, etc...
version: 3.1.3
homepage: https://github.com/gmpassos/swiss_knife

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  intl: ^0.18.0
  resource_portable: ^3.0.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.1
  dependency_validator: ^3.2.2
  collection: ^1.17.0
  coverage: ^1.6.1

#dependency_overrides:
#  resource_portable:
#    path: ../resource_portable

