name: swiss_knife
description: Dart Useful Tools - collections, math, date, uri, json, events, resources, regexp, etc...
version: 3.2.3
homepage: https://github.com/gmpassos/swiss_knife

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  intl: ^0.19.0
  resource_portable: ^3.1.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.14
  dependency_validator: ^4.1.2
  collection: ^1.18.0
  coverage: ^1.11.1

#dependency_overrides:
#  resource_portable:
#    path: ../resource_portable

