name: swiss_knife
description: Dart Useful Tools - collections, math, date, uri, json, events, resources, regexp, etc...
version: 3.3.0
homepage: https://github.com/gmpassos/swiss_knife

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  intl: ^0.20.2
  resource_portable: ^3.1.2

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
  dependency_validator: ^4.1.2
  collection: ^1.19.0
  coverage: ^1.11.1

#dependency_overrides:
#  resource_portable:
#    path: ../resource_portable

