name: swiss_knife
description: Dart Useful Tools - collections, math, date, uri, json, events, resources, regexp, etc...
version: 3.2.0
homepage: https://github.com/gmpassos/swiss_knife

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  intl: ^0.19.0
  resource_portable: ^3.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
  dependency_validator: ^3.2.3
  collection: ^1.18.0
  coverage: ^1.7.2

#dependency_overrides:
#  resource_portable:
#    path: ../resource_portable

